In [28]:
# dataset load kr rhe h

import pandas as pd

df = pd.read_csv(
    "../data/DataCoSupplyChainDataset.csv",
    encoding="latin-1"
)

df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [29]:
# columns check kr rhe h

print("Total columns:", len(df.columns))
print(df.columns.tolist())

Total columns: 53
['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)', 'Benefit per order', 'Sales per customer', 'Delivery Status', 'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City', 'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id', 'Customer Lname', 'Customer Password', 'Customer Segment', 'Customer State', 'Customer Street', 'Customer Zipcode', 'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market', 'Order City', 'Order Country', 'Order Customer Id', 'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id', 'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id', 'Order Item Product Price', 'Order Item Profit Ratio', 'Order Item Quantity', 'Sales', 'Order Item Total', 'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status', 'Order Zipcode', 'Product Card Id', 'Product Category Id', 'Product Description', 'Product Image', 'Product Name', 'Product Price', 'Product Status', 'shipping date (DateOrders)', 'Shipping Mode']

In [30]:
# dataset ka size dekh rhe h

print("Shape:", df.shape)

# dataset ki information dekh rhe h

df.info()

# numerical columns ka basic summary

df.describe()

Shape: (180519, 53)
<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  str
 9   Customer City                  180519 non-null  str
 10  Customer Country               180519 non-null  str
 11  Customer Email                 180519 non-null  str
 12  Customer Fname                 180519 non-null  str
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  str
 15  Customer Password              180519 non-null  str
 16  Customer Segment               180519 non-null  str
 17  Customer State                 180519 non-null  str
 18  Customer Street                180519 non-null  str
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  str
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  str
 25  Order City                     180519 non-null  str
 26  Order Country                  180519 non-null  str
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  str
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  str
 41  Order State                    180519 non-null  str
 42  Order Status                   180519 non-null  str
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  str
 48  Product Name                   180519 non-null  str
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  str
 52  Shipping Mode                  180519 non-null  str
dtypes: float64(15), int64(14), str(24)
memory usage: 73.0 MB

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Price,Product Status
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180516.000000,180519.000000,180519.000000,...,180519.000000,180519.000000,180519.000000,180519.000000,24840.000000,180519.000000,180519.000000,0.0,180519.000000,180519.0
mean,3.497654,2.931847,21.974989,183.107609,0.548291,31.851451,6691.379495,35921.126914,5.443460,29.719955,...,2.127638,203.772096,183.107609,21.974989,55426.132327,692.509764,31.851451,NaN,141.232550,0.0
std,1.623722,1.374449,104.433526,120.043670,0.497664,15.640064,4162.918106,37542.461122,1.629246,9.813646,...,1.453451,132.273077,120.043670,104.433526,31919.279101,336.446807,15.640064,NaN,139.732492,0.0
min,0.000000,0.000000,-4274.979980,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,-33.937553,...,1.000000,9.990000,7.490000,-4274.979980,1040.000000,19.000000,2.000000,NaN,9.990000,0.0
25%,2.000000,2.000000,7.000000,104.379997,0.000000,18.000000,3258.500000,725.000000,4.000000,18.265432,...,1.000000,119.980003,104.379997,7.000000,23464.000000,403.000000,18.000000,NaN,50.000000,0.0
50%,3.000000,4.000000,31.520000,163.990005,1.000000,29.000000,6457.000000,19380.000000,5.000000,33.144863,...,1.000000,199.919998,163.990005,31.520000,59405.000000,627.000000,29.000000,NaN,59.990002,0.0
75%,5.000000,4.000000,64.800003,247.399994,1.000000,45.000000,9779.000000,78207.000000,7.000000,39.279617,...,3.000000,299.950012,247.399994,64.800003,90008.000000,1004.000000,45.000000,NaN,199.990005,0.0
max,6.000000,4.000000,911.799988,1939.989990,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,...,5.000000,1999.989990,1939.989990,911.799988,99301.000000,1363.000000,76.000000,NaN,1999.989990,0.0

In [31]:
# missing values ka percentage check kr rhe h

missing = df.isnull().sum()
missing_percent = (missing / len(df)) * 100

missing_percent[missing_percent > 0].sort_values(ascending=False)

Product Description    100.000000
Order Zipcode           86.239676
Customer Lname           0.004432
Customer Zipcode         0.001662
dtype: float64

In [32]:
# pura empty column remove kr rhe h

df = df.drop(columns=["Product Description"])

In [33]:
# bahut zyada missing values wala column remove kr rhe h

df = df.drop(columns=["Order Zipcode"])

In [34]:
# customer last name ki missing values fill kr rhe h

df["Customer Lname"] = df["Customer Lname"].fillna(
    df["Customer Lname"].mode()[0]
)

In [35]:
# customer zipcode ki missing values fill kr rhe h

df["Customer Zipcode"] = df["Customer Zipcode"].fillna(
    df["Customer Zipcode"].median()
)

In [36]:
# dobara missing values check kr rhe h

df.isnull().sum()[df.isnull().sum() > 0]

Series([], dtype: int64)

In [37]:
# duplicate rows check kr rhe h

df.duplicated().sum()

np.int64(0)

In [38]:
# saare columns dekh rhe h

df.columns.tolist()

['Type',
 'Days for shipping (real)',
 'Days for shipment (scheduled)',
 'Benefit per order',
 'Sales per customer',
 'Delivery Status',
 'Late_delivery_risk',
 'Category Id',
 'Category Name',
 'Customer City',
 'Customer Country',
 'Customer Email',
 'Customer Fname',
 'Customer Id',
 'Customer Lname',
 'Customer Password',
 'Customer Segment',
 'Customer State',
 'Customer Street',
 'Customer Zipcode',
 'Department Id',
 'Department Name',
 'Latitude',
 'Longitude',
 'Market',
 'Order City',
 'Order Country',
 'Order Customer Id',
 'order date (DateOrders)',
 'Order Id',
 'Order Item Cardprod Id',
 'Order Item Discount',
 'Order Item Discount Rate',
 'Order Item Id',
 'Order Item Product Price',
 'Order Item Profit Ratio',
 'Order Item Quantity',
 'Sales',
 'Order Item Total',
 'Order Profit Per Order',
 'Order Region',
 'Order State',
 'Order Status',
 'Product Card Id',
 'Product Category Id',
 'Product Image',
 'Product Name',
 'Product Price',
 'Product Status',
 'shipping date (DateOrders)',
 'Shipping Mode']

In [39]:
# personal aur useless columns remove kr rhe h

df = df.drop(columns=[
    "Customer Email",
    "Customer Fname",
    "Customer Lname",
    "Customer Password",
    "Customer Street",
    "Product Image"
])

In [40]:
# columns kitne bache check kr rhe h

print("Columns:", len(df.columns))

Columns: 45

In [41]:
# date columns ko datetime me convert kr rhe h

df["order date (DateOrders)"] = pd.to_datetime(
    df["order date (DateOrders)"]
)

df["shipping date (DateOrders)"] = pd.to_datetime(
    df["shipping date (DateOrders)"]
)

In [42]:
# date ka datatype check kr rhe h

print(df["order date (DateOrders)"].dtype)
print(df["shipping date (DateOrders)"].dtype)

datetime64[us]
datetime64[us]

In [43]:
# target ki values check kr rhe h

df["Late_delivery_risk"].value_counts()

Late_delivery_risk
1    98977
0    81542
Name: count, dtype: int64

In [44]:
# target ka percentage check kr rhe h

df["Late_delivery_risk"].value_counts(normalize=True) * 100

Late_delivery_risk
1    54.829132
0    45.170868
Name: proportion, dtype: float64

In [45]:
# actual aur scheduled shipping ka difference nikal rhe h

df["Delay_Days"] = (
    df["Days for shipping (real)"]
    - df["Days for shipment (scheduled)"]
)

df[["Days for shipping (real)", "Days for shipment (scheduled)", "Delay_Days"]].head()

   Days for shipping (real)  Days for shipment (scheduled)  Delay_Days
0                         3                              4          -1
1                         5                              4           1
2                         4                              4           0
3                         3                              4          -1
4                         2                              4          -2

In [46]:
# delay ko categories me divide kr rhe h

df["Delay_Category"] = pd.cut(
    df["Delay_Days"],
    bins=[-100, 0, 2, 100],
    labels=["Early_On_Time", "Small_Delay", "High_Delay"]
)

df["Delay_Category"].value_counts()

Delay_Category
Small_Delay      89365
Early_On_Time    77119
High_Delay       14035
Name: count, dtype: int64

In [51]:
# months check kr rhe h
print(df.columns.tolist())

['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)', 'Benefit per order', 'Sales per customer', 'Delivery Status', 'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City', 'Customer Country', 'Customer Id', 'Customer Segment', 'Customer State', 'Customer Zipcode', 'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market', 'Order City', 'Order Country', 'Order Customer Id', 'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id', 'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id', 'Order Item Product Price', 'Order Item Profit Ratio', 'Order Item Quantity', 'Sales', 'Order Item Total', 'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status', 'Product Card Id', 'Product Category Id', 'Product Name', 'Product Price', 'Product Status', 'shipping date (DateOrders)', 'Shipping Mode', 'Delay_Days', 'Delay_Category']

In [52]:
# Step 1: date column ko datetime type me convert karo
df['order date (DateOrders)'] = pd.to_datetime(df['order date (DateOrders)'])

# Step 2: ab Month column bana sakte ho
df['Month'] = df['order date (DateOrders)'].dt.month

# ab yeh chalega
df["Month"].value_counts()

Month
1     17979
5     15976
7     15922
3     15919
8     15912
9     15489
4     15435
6     15139
2     14529
10    12955
12    12764
11    12500
Name: count, dtype: int64

In [53]:
# top 3 months by order volume ko peak season maan rahe hain
peak_months = [1, 5, 7]
df['Peak_Season'] = df['Month'].apply(lambda x: 1 if x in peak_months else 0)

In [54]:
# 1. Peak season flag (based on actual top months)
peak_months = [1, 5, 7]
df['Peak_Season'] = df['Month'].apply(lambda x: 1 if x in peak_months else 0)

# 2. Weekend flag
df['Order_Day'] = df['order date (DateOrders)'].dt.dayofweek
df['Is_Weekend'] = df['Order_Day'].apply(lambda x: 1 if x >= 5 else 0)

# 3. Shipping delay gap (scheduled vs real)
df['Shipping_Gap'] = df['Days for shipping (real)'] - df['Days for shipment (scheduled)']

# 4. Order value category (Sales column ko bins me daalo)
df['Order_Value_Category'] = pd.cut(df['Sales'], bins=[0,100,300,1000,float('inf')],
                                     labels=['Low','Medium','High','Very High'])

# 5. Quick insight check - region wise late delivery rate
df.groupby('Order Region')['Late_delivery_risk'].mean().sort_values(ascending=False)

Order Region
Central Africa     0.579606
South Asia         0.562670
East Africa        0.559395
Western Europe     0.558486
South of  USA      0.557726
Eastern Europe     0.556633
East of USA        0.556616
Southeast Asia     0.555299
Central Asia       0.553345
West Asia          0.552837
US Center          0.552404
Central America    0.547546
North Africa       0.545173
Southern Europe    0.543845
Eastern Asia       0.543269
South America      0.543087
Northern Europe    0.540441
Oceania            0.540205
West of USA        0.539597
Southern Africa    0.533276
Caribbean          0.530777
West Africa        0.528409
Canada             0.488008
Name: Late_delivery_risk, dtype: float64

In [55]:
# 1. Check final missing values
print(df.isnull().sum().sort_values(ascending=False).head(10))

# 2. Drop irrelevant/redundant columns (adjust list based on your data)
drop_cols = ['Customer Zipcode', 'Product Status', 'Order Status']  # example — check what's actually useless
df.drop(columns=drop_cols, inplace=True, errors='ignore')

# 3. Final shape check
print(df.shape)

# 4. Export cleaned dataset
df.to_csv('cleaned_supply_chain.csv', index=False)
print("Saved successfully")

Type                             0
Days for shipping (real)         0
Days for shipment (scheduled)    0
Benefit per order                0
Sales per customer               0
Delivery Status                  0
Late_delivery_risk               0
Category Id                      0
Category Name                    0
Customer City                    0
dtype: int64
(180519, 50)
Saved successfully